using System;
using System.Collections.Generic;
using System.Collections;
using System.Globalization;
using System.Reflection;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace FuryAutoPatcher;
public static class Program 
{
    private static readonly ModKey FuryModKey = ModKey.FromNameAndExtension("Fury - Animal Taming of Skyrim.esl");
    private static readonly FormKey FuryFormKey = new(FuryModKey, 0x05E1AA);

    private static readonly List<string> FuryFL_EditorIDs = new() {
        "FURY_FormList_RacesFrom", 
        "FURY_FormList_RacesTo", 
        "FURY_Formlist_PetLevels", 
        "FURY_FormList_PetStrengthValues", 
        "FURY_FormList_FoodTypes"};
    
    private static readonly string tamedKeyword = "Futhark_InjectedKeyword_Race_IsTamedAnimalRace";

    private static Lazy<Settings> _settings = null!;

    private static double  setBaseLevel(float magicka_stat, float stamina_stat, float health_stat) {
        return Math.Floor(Math.Max(magicka_stat - 100, 0)/10) 
            + Math.Floor(Math.Max(stamina_stat - 100, 0)/10) 
            + Math.Floor(Math.Max(health_stat - 100, 0)/10);
    }

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "Settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "FuryAuto.esp")
            .Run(args);
    }
    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        if (!state.LoadOrder.ContainsKey(FuryModKey)) {
            Console.WriteLine("ERROR: Fury not Detected!");
            return;
        }

        Console.WriteLine("SUCCESS: Fury detected!");
        Dictionary<string, IFormListGetter> FL_Lookup = new();
        Dictionary<string, IFormList> Patch_Lookup = new();
        
        foreach (string FL_ID in FuryFL_EditorIDs) {
            if (state.LinkCache.TryResolve<IFormListGetter>(FL_ID, out var
                        FL)) {

                var overiddingFL = state.PatchMod.FormLists.GetOrAddAsOverride(FL);
                if (FL_Lookup.TryAdd(FL_ID, FL)) {
                    Console.WriteLine("Warning: Tried to add an existing FormList.");
                };
                 
                if (Patch_Lookup.TryAdd(FL_ID, overiddingFL)) {
                    Console.WriteLine("Warning: Tried to add an existing FormList.");
                }

            } else {
                Console.WriteLine($"ERROR: {FL_ID} not found!");
                return; 
            }
        }
        
        Console.WriteLine("SUCCESS: Fury Formlists found!");
        // get all animal races in Fury
        HashSet<FormKey> baseFuryRaces= new HashSet<FormKey>();
        
        foreach (var item in FL_Lookup["FURY_FormList_RacesFrom"].Items) {
            if (state.LinkCache.TryResolve<IRaceGetter>(item.FormKey, out var race)) {
               baseFuryRaces.Add(race.FormKey); 
            }
        }

        foreach (var item in FL_Lookup["FURY_FormList_RacesTo"].Items) {
            if (state.LinkCache.TryResolve<IRaceGetter>(item.FormKey, out var race)) {
               baseFuryRaces.Add(race.FormKey); 
            }
        }
        
        Console.WriteLine("SUCCESS: Fury races cached!");


        // get all animal races not in fury and patch
        if (!state.LinkCache.TryResolve<IKeywordGetter>(tamedKeyword, out var tamedKeyObj)) {
            Console.WriteLine("WARNING: Tameable Keyword not FOUND. Please inform the mod author if you did not change any keywords.");
        }
        
        // This should not fail
        var racesFrom = Patch_Lookup["FURY_FormList_RacesFrom"];
        var racesTo = Patch_Lookup["FURY_FormList_RacesTo"];
        var levelsFL = Patch_Lookup["FURY_Formlist_PetLevels"];
        var strengthsFL = Patch_Lookup["FURY_FormList_PetStrengthValues"];
        var foodsFL = Patch_Lookup["FURY_FormList_FoodTypes"];

        foreach (IRaceGetter race in state.LoadOrder.PriorityOrder.Race().WinningOverrides()) {
            if (!baseFuryRaces.Contains(race.FormKey) && !_settings.Value.ExcludeRaces.Contains(race) && race.HasKeyword("ActorTypeAnimal", state.LinkCache)) {
                
                racesFrom.Items.Add(race); 
                
                var petRace = state.PatchMod.Races.DuplicateInAsNewRecord(race);
                petRace.Keywords ??= new Noggog.ExtendedList<IFormLinkGetter<IKeywordGetter>>();
                petRace.Keywords.Add(tamedKeyObj!.ToLink<IKeywordGetter>());
                petRace.EditorID = $"FURY_Ext_{petRace.EditorID}";
                racesTo.Items.Add(petRace);
                
                // I do not know how to do this better, sorry
                var strengthGlob = state.PatchMod.Globals.AddNewShort();
                strengthGlob.EditorID = $"FURY_Ext_Global_Weight_{petRace.EditorID}";

                var levelGlob = state.PatchMod.Globals.AddNewShort();
                levelGlob.EditorID = $"FURY_Ext_Global_Level_{petRace.EditorID}";

                var foodGlob = state.PatchMod.Globals.AddNewShort();
                foodGlob.EditorID = $"FURY_Ext_Global_FoodType_{petRace.EditorID}";

                switch (petRace.Size) {
                    case Mutagen.Bethesda.Skyrim.Size.Small:
                        strengthGlob.Data = 4;
                        levelGlob.Data = 10;
                        break;
                    case Mutagen.Bethesda.Skyrim.Size.Medium:
                        strengthGlob.Data = 6;
                        levelGlob.Data = 15;
                        break;
                    case Mutagen.Bethesda.Skyrim.Size.Large:
                        strengthGlob.Data = 8;
                        levelGlob.Data = 20;
                        break;
                    case Mutagen.Bethesda.Skyrim.Size.ExtraLarge:
                        strengthGlob.Data = 10;
                        levelGlob.Data = 25;
                        break;
                }

                strengthsFL.Items.Add(strengthGlob);
                levelsFL.Items.Add(levelGlob);
                foodsFL.Items.Add(foodGlob);
                
                Console.WriteLine($"SUCCESS: Processed EditorID: {petRace.EditorID}");
            }
        }    

        Console.WriteLine("Successfully added all animals to Fury!");
    }
}
