using System;
using System.Collections.Generic;
using System.Collections;
using System.Globalization;
using System.Reflection;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace FuryAutoPatcher;
public static class Program 
{
    private static readonly ModKey FuryModKey = ModKey.FromNameAndExtension("Fury - Animal Taming of Skyrim.esl");
    private static readonly FormKey FuryFormKey = new(FuryModKey, 0x05E1AA);

    private static readonly List<string> FuryFL_EditorIDs = new() {
        "FURY_FormList_RacesFrom", 
        "FURY_FormList_RacesTo", 
        "FURY_Formlist_PetLevels", 
        "FURY_FormList_PetStrengthValues", 
        "FURY_FormList_FoodTypes",
        "FURY_FormList_PetActorsBothGenders",
        "FURY_FormList_PetActorsF",
        "FURY_FormList_PetActorsM",
    };
    
    private static readonly string tameableKeyword = "Futhark_InjectedKeyword_Race_IsTameable";
    private static readonly string tamedKeyword = "Futhark_InjectedKeyword_Race_IsTamedAnimalRace";
    
    private static readonly string globalFoodAll = "FURY_Global_FoodType_AshHopper";

    private static Lazy<Settings> _settings = null!;

    private static double  setBaseLevel(float magicka_stat, float stamina_stat, float health_stat) {
        return Math.Floor(Math.Max(magicka_stat - 100, 0)/10) 
            + Math.Floor(Math.Max(stamina_stat - 100, 0)/10) 
            + Math.Floor(Math.Max(health_stat - 100, 0)/10);
    }

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "Settings.json", out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "FuryAuto.esp")
            .Run(args);
    }

    private static bool TryCreateSkin(IRaceGetter race, IPatcherState<ISkyrimMod, ISkyrimModGetter> state, out IArmorGetter? res) {
        res = default;;
        if (!race.Skin.TryResolve<IArmorGetter>(state.LinkCache, out var skin)) {
            return false;
        }

        var skin_dup = state.PatchMod.Armors.DuplicateInAsNewRecord(skin);
        skin_dup.Race.SetTo(race);
        skin_dup.EditorID = $"FURY_Skin_{skin_dup.EditorID}";
        skin_dup.Armature.Clear(); 

        foreach (var armaLink in skin.Armature) {
            if (!armaLink.TryResolve<IArmorAddonGetter>(state.LinkCache, out var arma)) {
                return false;
            }
            
            var arma_dup = state.PatchMod.ArmorAddons.DuplicateInAsNewRecord(arma);
            arma_dup.Race.SetTo(race);
            arma_dup.EditorID = $"FURY_Skin_{arma_dup.EditorID}";
            skin_dup.Armature.Add(arma_dup);
        }
        
        res = skin_dup;
        return true;
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        if (!state.LoadOrder.ContainsKey(FuryModKey)) {
            Console.WriteLine("ERROR: Fury not Detected!");
            return;
        }

        Console.WriteLine("SUCCESS: Fury detected!");
        Dictionary<string, IFormListGetter> FL_Lookup = new();
        Dictionary<string, IFormList> Patch_Lookup = new();
        
        foreach (string FL_ID in FuryFL_EditorIDs) {
            if (state.LinkCache.TryResolve<IFormListGetter>(FL_ID, out var
                        FL)) {

                var overiddingFL = state.PatchMod.FormLists.GetOrAddAsOverride(FL);
                if (FL_Lookup.TryAdd(FL_ID, FL)) {
                    Console.WriteLine("Warning: Tried to add an existing FormList.");
                };
                 
                if (Patch_Lookup.TryAdd(FL_ID, overiddingFL)) {
                    Console.WriteLine("Warning: Tried to add an existing FormList.");
                }

            } else {
                Console.WriteLine($"ERROR: {FL_ID} not found!");
                return; 
            }
        }
        
        Console.WriteLine("SUCCESS: Fury Formlists found!");

        // get all animal races in Fury
        HashSet<FormKey> baseRaces = new HashSet<FormKey>();
        foreach (var item in FL_Lookup["FURY_FormList_RacesFrom"].Items) {
            if (state.LinkCache.TryResolve<IRaceGetter>(item.FormKey, out var race)) {
               baseRaces.Add(race.FormKey); 
            }
        }

        foreach (var item in FL_Lookup["FURY_FormList_RacesTo"].Items) {
            if (state.LinkCache.TryResolve<IRaceGetter>(item.FormKey, out var race)) {
               baseRaces.Add(race.FormKey); 
            }
        }
        
        Console.WriteLine("SUCCESS: Fury races cached!");


        // Keywords to assign
        if (!state.LinkCache.TryResolve<IKeywordGetter>(tamedKeyword, out var tamedKeyObj)) {
            Console.WriteLine("WARNING: Tamed Keyword not FOUND. Please inform the mod author if you did not change any keywords.");
        }

        if (!state.LinkCache.TryResolve<IKeywordGetter>(tameableKeyword, out var tameableKeyObj)) {
            Console.WriteLine("WARNING: Tameable Keyword not FOUND. Please inform the mod author if you did not change any keywords.");
        }
        
        // if I know any better, I wouldn't do this... sadly I don't
        if (!state.LinkCache.TryResolve<IGlobalShortGetter>(globalFoodAll, out var globalFoodAllObj)) {
            Console.WriteLine($"ERROR: Global: {globalFoodAll} not FOUND. Please inform the mod author if no EditorIDs were changed");
            return;
        }

        // This should not fail
        var racesFrom = Patch_Lookup["FURY_FormList_RacesFrom"];
        var racesTo = Patch_Lookup["FURY_FormList_RacesTo"];
        var levelsFL = Patch_Lookup["FURY_Formlist_PetLevels"];
        var strengthsFL = Patch_Lookup["FURY_FormList_PetStrengthValues"];
        var foodsFL = Patch_Lookup["FURY_FormList_FoodTypes"];
        var actorFLM = Patch_Lookup["FURY_FormList_PetActorsF"];
        var actorFLF = Patch_Lookup["FURY_FormList_PetActorsM"];
        var actorFLB = Patch_Lookup["FURY_FormList_PetActorsBothGenders"];
 
        // Flags to assign
        var femaleFlag = Mutagen.Bethesda.Skyrim.NpcConfiguration.Flag.Female;
        var affectsDetectionFlag = Mutagen.Bethesda.Skyrim.NpcConfiguration.Flag.DoesntAffectStealthMeter;
        var enableDialogue = Mutagen.Bethesda.Skyrim.Race.Flag.AllowPcDialog;
        
        // AIData to assign
        var helpsAllies = Mutagen.Bethesda.Skyrim.Assistance.HelpsAllies;

        foreach (INpcGetter npc in state.LoadOrder.PriorityOrder.Npc().WinningOverrides()) {
            IRaceGetter race = npc.Race.Resolve(state.LinkCache);
            if (!baseRaces.Contains(race.FormKey) && race.HasKeyword("ActorTypeAnimal", state.LinkCache)) {
                
                // make only 2 unique actors per race, NEVER reuse races
                baseRaces.Add(race.FormKey);
                
                var orRace = state.PatchMod.Races.GetOrAddAsOverride(race);
                orRace.Keywords ??= new Noggog.ExtendedList<IFormLinkGetter<IKeywordGetter>>();
                orRace.Keywords.Add(tameableKeyObj!.ToLink<IKeywordGetter>());

                var petRace = state.PatchMod.Races.DuplicateInAsNewRecord(race);
                petRace.Keywords ??= new Noggog.ExtendedList<IFormLinkGetter<IKeywordGetter>>();
                petRace.Keywords.Add(tamedKeyObj!.ToLink<IKeywordGetter>());
                petRace.Flags |= enableDialogue;
                petRace.EditorID = $"FURY_EXT_Race_Pet_{petRace.EditorID}";
                if (!TryCreateSkin(petRace, state, out var skin)) {
                    Console.WriteLine($"Warning: Skin for {petRace.EditorID} created;");
                } else {
                    petRace.Skin.SetTo(skin);
                } 

                var oActor = state.PatchMod.Npcs.GetOrAddAsOverride(npc);
                
                var petActorM = state.PatchMod.Npcs.DuplicateInAsNewRecord(npc); 
                var petActorF = state.PatchMod.Npcs.DuplicateInAsNewRecord(npc);
                
                petActorM.EditorID = $"FURY_EXT_Actor_Pet_{npc.EditorID}M";
                petActorF.EditorID = $"FURY_EXT_Actor_Pet_{npc.EditorID}F";


                if (!npc.Configuration.Flags.HasFlag(femaleFlag)) {
                    petActorF.Configuration.Flags |= femaleFlag;
                } else {
                    petActorM.Configuration.Flags &= ~femaleFlag;
                }

                petActorF.Configuration.Flags |= affectsDetectionFlag;
                petActorM.Configuration.Flags |= affectsDetectionFlag;
                petActorF.Configuration.Level = new NpcLevel() {Level = 1};
                petActorM.Configuration.Level = new NpcLevel() {Level = 1};
                petActorF.AIData.Assistance = helpsAllies;
                petActorM.AIData.Assistance = helpsAllies;
                petActorF.Race = petRace.ToLink();
                petActorM.Race = petRace.ToLink();
                petActorF.WornArmor.SetTo(skin);
                petActorM.WornArmor.SetTo(skin);

                // I do not know how to do this better, sorry
                var strengthGlob = state.PatchMod.Globals.AddNewShort();
                strengthGlob.EditorID = $"FURY_EXT_Global_Weight_{petRace.EditorID}";

                var levelGlob = state.PatchMod.Globals.AddNewShort();
                levelGlob.EditorID = $"FURY_EXT_Global_Level_{petRace.EditorID}";

                // var foodGlob = state.PatchMod.Globals.AddNewShort();
                // foodGlob.EditorID = $"FURY_EXT_Global_FoodType_{petRace.EditorID}";
                // foodGlob.Data = 0;

                switch (petRace.Size) {
                    case Mutagen.Bethesda.Skyrim.Size.Small:
                        strengthGlob.Data = 2;
                        levelGlob.Data = 10;
                        break;
                    case Mutagen.Bethesda.Skyrim.Size.Medium:
                        strengthGlob.Data = 3;
                        levelGlob.Data = 15;
                        break;
                    case Mutagen.Bethesda.Skyrim.Size.Large:
                        strengthGlob.Data = 4;
                        levelGlob.Data = 20;
                        break;
                    case Mutagen.Bethesda.Skyrim.Size.ExtraLarge:
                        strengthGlob.Data = 6;
                        levelGlob.Data = 25;
                        break;
                }
                
                racesFrom.Items.Add(race);
                racesTo.Items.Add(petRace);
                strengthsFL.Items.Add(strengthGlob);
                levelsFL.Items.Add(levelGlob);
                foodsFL.Items.Add(globalFoodAllObj.ToLink<ISkyrimMajorRecordGetter>());
                actorFLF.Items.Add(petActorF);
                actorFLM.Items.Add(petActorM);

                // Must be appended in this order by convention
                actorFLB.Items.Add(petActorF);
                actorFLB.Items.Add(petActorM);
                
                Console.WriteLine($"SUCCESS: Processed EditorID: {petRace.EditorID}");
            }
        }    

        Console.WriteLine("Successfully added all animals to Fury!");
    }
}
